import Layout from "@components/Layout";

import { MaxWidthWrapper } from "@components/common/Containers";
import { Description, SubTitle } from "@components/common/Text";

export default function Home() {
	return (
		<Layout pageName="home">
			{/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

			<MaxWidthWrapper>
				<div className="px-2">
					<p className="text-5xl py-3 font-bold  text-red-50">Hi, I'm John</p>
					<div className="text-base py-3 text-gray-300 font-normal">
						{/* <SubTitle>Velit nulla nostrud qui commodo commodo Lorem.</SubTitle> */}
						<br />
						<Description>
							Id ex ea do magna culpa esse. Sint pariatur ipsum consectetur
							mollit. Proident laboris ut sint sunt quis ipsum. Dolore id ut ad
							dolor consequat veniam incididunt tempor velit ipsum anim ad
							dolor.
						</Description>
					</div>
				</div>
			</MaxWidthWrapper>
		</Layout>
	);
}
